server:
  port: 8082

spring:
  application:
    name: index-gather-store-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: http://127.0.0.1:8858

dubbo:
  registry:
    address: nacos://127.0.0.1:8848
    register-mode: instance
  protocol:
    name: dubbo
    port: -1
    serialization: hessian2

management:
  endpoints:
    web:
      exposure:
        include: '*'





