server:
  port: 8081

spring:
  application:
    name: third-part-index-data-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8858

dubbo:
  registry:
    address: nacos://localhost:8848
    register-mode: instance
  protocol:
    name: dubbo
    port: -1
    serialization: hessian2

management:
  endpoints:
    web:
      exposure:
        include: '*'





